# @package _global_

defaults:
  - base
scenes_abspath: /home/luohy/MyRepository/MyDataSets/Data/Object/bed
scenes_name: Bed
scenes:
  - scene_id: 0
    scene_path: ./
    filter_list: []
    rigidbody_list: []
    articulation_list: []
    objects: []
    collections:
      - obj_id: 0
        obj_path: 3FO3WIUHH47S/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.5618680119514465]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 1
        obj_path: 3FO3WJCWAMO2/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.505977988243103]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 2
        obj_path: 3FO3WJX7K3CT/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.5398110151290894]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 3
        obj_path: 3FO3WIUECT24/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.5826169848442078]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 4
        obj_path: 3FO3WIUHI604/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.6555259823799133]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 5
        obj_path: 3FO3WITG1WUF/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.7169830203056335]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 6
        obj_path: 3FO3WX5EBVML/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.4945470094680786]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 7
        obj_path: 3FO3WJ6EQAN5/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.8504530191421509]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 8
        obj_path: 3FO3WJWSCMU2/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.6503599882125854]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 9
        obj_path: 3FO3WJCU3JC0/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.553695023059845]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 10
        obj_path: 3FO3WQTLHGN7/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.584863007068634]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 11
        obj_path: 3FO3WIUHHKWX/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.647765040397644]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 12
        obj_path: 3FO3WITQO85R/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.544730007648468]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 13
        obj_path: 3FO3WITD70DJ/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.8198850154876709]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 14
        obj_path: 3FO3WITHJNK7/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.6641409993171692]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 15
        obj_path: 3FO3WJD0A2BA/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.5750409960746765]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 16
        obj_path: 3FO3WITQNX4O/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.6961609721183777]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 17
        obj_path: 3FO3WJD073NE/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.7796090245246887]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 18
        obj_path: 3FO3WIUBH1GY/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.6475499868392944]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 19
        obj_path: 3FO3WIUHHAVU/Instance.usda
        obj_name: Bed
        obj_translate: [0.0, 0.0, 0.7578660249710083]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
