# @package _global_

defaults:
  - base
scenes_abspath: /home/luohy/MyRepository/MyDataSets/Data/Object/Toy
scenes_name: Toy
scenes:
  - scene_id: 0
    scene_path: ./
    filter_list: []
    rigidbody_list: []
    articulation_list: []
    objects: []
    collections:
      - obj_id: 0
        obj_path: 3FO3U25AYHUF/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.09601791203022003]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 1
        obj_path: 3FO42IAR32XL/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.17764200270175934]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 2
        obj_path: 3FO3P5GVKUEQ/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.20724034309387207]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 3
        obj_path: 3FO3Y3QAPBHB/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.07539534568786621]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 4
        obj_path: 3FO3Y2I29GH7/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.25526899099349976]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 5
        obj_path: 3FO4DOCCJQ75/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.15430599451065063]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 6
        obj_path: 3FO3Y2HRRAIU/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.08800379931926727]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 7
        obj_path: 3FO3WFUIRHB7/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.0885464996099472]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 8
        obj_path: 3FO3NNDFSD2S/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.08979178965091705]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 9
        obj_path: 3FO3URROBKH7/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.07274258136749268]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 10
        obj_path: 3FO3Y3WTU2TS/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.12178800255060196]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 11
        obj_path: 3FO3SX76DW2W/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.05992785841226578]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 12
        obj_path: 3FO3NNCTMYLD/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.12380611896514893]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 13
        obj_path: 3FO3U6ULUTLG/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.13196739554405212]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 14
        obj_path: 3FO3Y2IE7P3A/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.07016660273075104]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 15
        obj_path: 3FO3V3UCUGHA/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.11519510298967361]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 16
        obj_path: 3FO46NBRXGHX/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.14189200103282928]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 17
        obj_path: 3FO42UROG2KX/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.15919199585914612]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 18
        obj_path: 3FO44CX9XLAY/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.063612200319767]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 19
        obj_path: 3FO3UD8RJVR2/Instance.usda
        obj_name: Toy
        obj_translate: [0.0, 0.0, 0.26077568531036377]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
