# @package _global_

defaults:
  - base
scenes_abspath: /home/luohy/MyRepository/MyDataSets/Data/Object/bookcase
scenes_name: Bookcase
scenes:
  - scene_id: 0
    scene_path: ./
    filter_list: []
    rigidbody_list: []
    articulation_list: []
    objects: []
    collections:
      - obj_id: 0
        obj_path: 3FO44W6BLOS0/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.1924999952316284]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 1
        obj_path: 3FO44VSUF2E6/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.2050000429153442]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 2
        obj_path: 3FO3W5KKRMYB/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 0.8645925521850586]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 3
        obj_path: 3FO3X2XHWQTB/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 0.6675000190734863]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 4
        obj_path: 3FO3WXEII0QK/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 0.9886350035667419]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 5
        obj_path: 3FO3WXEIHT2I/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.1898000240325928]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 6
        obj_path: 3FO3X2LQX6KA/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 0.4950000047683716]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 7
        obj_path: 3FO3X2LTFRPH/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 0.9107990264892578]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 8
        obj_path: 3FO3WXEOHBQ6/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.0823400020599365]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 9
        obj_path: 3FO3WXEC22Y0/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.166599988937378]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 10
        obj_path: 3FO3X16CL9H0/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.2000000476837158]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 11
        obj_path: 3FO3WXEKXVP9/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.0002599954605103]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 12
        obj_path: 3FO3WXEC0CRH/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.1009199619293213]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 13
        obj_path: 3FO3WXEDMKML/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.0004700422286987]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 14
        obj_path: 3FO3X2VDV1B7/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 0.4650000035762787]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 15
        obj_path: 3FO3WXEOI05D/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.2000000476837158]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 16
        obj_path: 3FO3WXEII43L/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.1340299844741821]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 17
        obj_path: 3FO3X2VOO5KA/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 0.6150000095367432]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 18
        obj_path: 3FO3WXEG93UY/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.1002899408340454]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 19
        obj_path: 3FO3WXEC09FG/Instance.usda
        obj_name: Bookcase
        obj_translate: [0.0, 0.0, 1.0395900011062622]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
