# @package _global_

defaults:
  - base
scenes_abspath: /home/luohy/MyRepository/MyDataSets/Data/Object/box
scenes_name: Box
scenes:
  - scene_id: 0
    scene_path: ./
    filter_list: []
    rigidbody_list: []
    articulation_list: []
    objects: []
    collections:
      - obj_id: 0
        obj_path: 3FO4L8QDT1UG/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.054668501019477844]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 1
        obj_path: 3FO43KX2EEPF/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.13303300738334656]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 2
        obj_path: 3FO3UI2N01XO/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.10586246103048325]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 3
        obj_path: 3FO3RM3IN0CI/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.1740283966064453]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 4
        obj_path: 3FO4L6BX41JF/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.14656400680541992]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 5
        obj_path: 3FO4G4I6CG9T/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.12525099515914917]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 6
        obj_path: 3FO4B2C21Y3L/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.08006130158901215]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 7
        obj_path: 3FO4B2DH0BNH/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.07060465216636658]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 8
        obj_path: 3FO3UG35QQD6/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.23906269669532776]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 9
        obj_path: 3FO4IWGIWS0O/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.1252254992723465]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 10
        obj_path: 3FO4DNKRT0S4/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.09519235044717789]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 11
        obj_path: 3FO3VNQC53SP/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.0964665561914444]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 12
        obj_path: 3FO3UMY2FTD4/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.15345749258995056]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 13
        obj_path: 3FO4BSKXETCN/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.06662560254335403]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 14
        obj_path: 3FO4EQ9ULJ6R/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.21422000229358673]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 15
        obj_path: 3FO3SSL5GU5S/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.1882501244544983]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 16
        obj_path: 3FO4GWHC3WEY/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.2898310124874115]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 17
        obj_path: 3FO48JPFAN2C/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.10593000054359436]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 18
        obj_path: 3FO3S39JNRQY/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.29015037417411804]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 19
        obj_path: 3FO3S1T1H2QD/Instance.usda
        obj_name: Box
        obj_translate: [0.0, 0.0, 0.43884629011154175]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
