# @package _global_

defaults:
  - base
scenes_abspath: /home/luohy/MyRepository/MyDataSets/Data/Object/chair
scenes_name: Chair
scenes:
  - scene_id: 0
    scene_path: ./
    filter_list: []
    rigidbody_list: []
    articulation_list: []
    objects: []
    collections:
      - obj_id: 0
        obj_path: 3FO44WWRJFS9/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.9807469844818115]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 1
        obj_path: 3FO3WH1X6GBT/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.36194100975990295]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 2
        obj_path: 3FO3WDIUUJ5W/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.37194299697875977]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 3
        obj_path: 3FO3WH2WCWHN/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.46341198682785034]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 4
        obj_path: 3FO44ENVB7JD/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.37091100215911865]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 5
        obj_path: 3FO3WH1VG6GS/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.3518739938735962]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 6
        obj_path: 3FO3WH21227W/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.3768959939479828]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 7
        obj_path: 3FO3WDISMY3P/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.3700000047683716]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 8
        obj_path: 3FO3WDISVGO9/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.2905629873275757]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 9
        obj_path: 3FO3WH1XC3LI/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.3632720112800598]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 10
        obj_path: 3FO3U59GXQ0M/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.18631872534751892]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 11
        obj_path: 3FO3WH211R6T/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.42677050828933716]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 12
        obj_path: 3FO3WH214PTP/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.41739800572395325]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 13
        obj_path: 3FO3WH1X6QCW/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.3126069903373718]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 14
        obj_path: 3FO3UV6GSK2S/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.4283615052700043]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 15
        obj_path: 3FO44WWDNN7Y/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.47137999534606934]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 16
        obj_path: 3FO3WDISL8W7/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.3524959981441498]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 17
        obj_path: 3FO3WCRLM56Q/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.2957800030708313]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 18
        obj_path: 3FO3WHSUHB1H/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.3499020040035248]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 19
        obj_path: 3FO3WH1THO2B/Instance.usda
        obj_name: Chair
        obj_translate: [0.0, 0.0, 0.40992799401283264]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
