# @package _global_

defaults:
  - base
scenes_abspath: /home/luohy/MyRepository/MyDataSets/Data/Object/sofa
scenes_name: Sofa
scenes:
  - scene_id: 0
    scene_path: ./
    filter_list: []
    rigidbody_list: []
    articulation_list: []
    objects: []
    collections:
      - obj_id: 0
        obj_path: 3FO44W6BTT0F/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.41335898637771606]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 1
        obj_path: 3FO44W9V1B4C/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.3870429992675781]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 2
        obj_path: 3FO44W6C5BSK/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.3892430067062378]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 3
        obj_path: 3FO44W6BWAX6/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.3962770104408264]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 4
        obj_path: 3FO44W6AXY07/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.5592139959335327]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 5
        obj_path: 3FO44W69UD5N/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.373881995677948]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 6
        obj_path: 3FO44W69UN6Q/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.5222139954566956]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 7
        obj_path: 3FO44W6ACQOU/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.4618009924888611]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 8
        obj_path: 3FO44W696H8I/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.41578400135040283]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 9
        obj_path: 3FO44W6C58GJ/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.44964799284935]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 10
        obj_path: 3FO44W6C2X7U/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.3728159964084625]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 11
        obj_path: 3FO44W69U6GL/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.6381310224533081]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 12
        obj_path: 3FO44W6C2D5O/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.38795000314712524]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 13
        obj_path: 3FO44W698UT8/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.4503529965877533]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 14
        obj_path: 3FO44W6BWOBA/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.4086399972438812]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 15
        obj_path: 3FO44W6BYL6U/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.37169399857521057]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 16
        obj_path: 3FO44W69997C/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.4073309898376465]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 17
        obj_path: 3FO44W696NWK/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.45323699712753296]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 18
        obj_path: 3FO44W6C6GWW/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.5537629723548889]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
      - obj_id: 19
        obj_path: 3FO44W6BWEA7/Instance.usda
        obj_name: Sofa
        obj_translate: [0.0, 0.0, 0.37784698605537415]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
