# @package _global_

defaults:
  - base
scenes_abspath: /home/luohy/MyRepository/MyDataSets/Data/Object/chair
scenes_name: Chair
scenes:
  - scene_id: 3FO44WWRJFS9
    scene_path: 3FO44WWRJFS9
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.9807469844818115]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WH1X6GBT
    scene_path: 3FO3WH1X6GBT
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.36194100975990295]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WDIUUJ5W
    scene_path: 3FO3WDIUUJ5W
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.37194299697875977]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WH2WCWHN
    scene_path: 3FO3WH2WCWHN
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.46341198682785034]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO44ENVB7JD
    scene_path: 3FO44ENVB7JD
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.37091100215911865]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WH1VG6GS
    scene_path: 3FO3WH1VG6GS
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.3518739938735962]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WH21227W
    scene_path: 3FO3WH21227W
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.3768959939479828]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WDISMY3P
    scene_path: 3FO3WDISMY3P
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.3700000047683716]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WDISVGO9
    scene_path: 3FO3WDISVGO9
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.2905629873275757]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WH1XC3LI
    scene_path: 3FO3WH1XC3LI
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.3632720112800598]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3U59GXQ0M
    scene_path: 3FO3U59GXQ0M
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.18631872534751892]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WH211R6T
    scene_path: 3FO3WH211R6T
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.42677050828933716]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WH214PTP
    scene_path: 3FO3WH214PTP
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.41739800572395325]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WH1X6QCW
    scene_path: 3FO3WH1X6QCW
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.3126069903373718]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3UV6GSK2S
    scene_path: 3FO3UV6GSK2S
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.4283615052700043]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO44WWDNN7Y
    scene_path: 3FO44WWDNN7Y
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.47137999534606934]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WDISL8W7
    scene_path: 3FO3WDISL8W7
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.3524959981441498]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WCRLM56Q
    scene_path: 3FO3WCRLM56Q
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.2957800030708313]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WHSUHB1H
    scene_path: 3FO3WHSUHB1H
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.3499020040035248]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
  - scene_id: 3FO3WH1THO2B
    scene_path: 3FO3WH1THO2B
    filter_list: []
    rigidbody_list:
      - 0
    articulation_list: []
    objects:
      - obj_id: 0
        obj_path: Instance.usda
        obj_name: Instance.usda
        obj_translate: [0.0, 0.0, 0.40992799401283264]
        obj_rotateXYZW: [0.0, 0.0, 0.0, 1.0]
        obj_scale: [1.0, 1.0, 1.0]
